import type { LucideIcon } from 'lucide-react';
import {
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  Cat,
  Church,
  Circle,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Clock,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  MapPin,
  MoreHorizontal,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Scissors,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sprout,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wind,
  Wrench,
  Hammer,
  Zap,
} from 'lucide-react';

/**
 * Curated set of lucide icons offered by the category editor, keyed by lucide's
 * canonical kebab-case name (what we store in categories.icon_name). Resolving
 * by name works on both the server and the client, so DTOs stay serializable
 * (we ship the name across the RSC boundary, not the component).
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  // money / accounts
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'hand-coins': HandCoins,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  gem: Gem,
  receipt: Receipt,
  tag: Tag,
  briefcase: Briefcase,
  gift: Gift,
  // home / bills
  house: House,
  'building-2': Building2,
  zap: Zap,
  lightbulb: Lightbulb,
  droplets: Droplets,
  flame: Flame,
  wifi: Wifi,
  plug: Plug,
  wind: Wind,
  bed: Bed,
  // food
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  cake: Cake,
  // transport / travel
  car: Car,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  plane: Plane,
  'map-pin': MapPin,
  umbrella: Umbrella,
  // health / family
  'heart-pulse': HeartPulse,
  heart: Heart,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  'paw-print': PawPrint,
  // lifestyle / leisure
  clapperboard: Clapperboard,
  film: Film,
  tv: Tv,
  music: Music,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  shirt: Shirt,
  scissors: Scissors,
  // education / work / misc
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  smartphone: Smartphone,
  laptop: Laptop,
  phone: Phone,
  hammer: Hammer,
  wrench: Wrench,
  shield: Shield,
  'shield-check': ShieldCheck,
  church: Church,
  sprout: Sprout,
  leaf: Leaf,
  'flower-2': Flower2,
  sun: Sun,
  clock: Clock,
  'more-horizontal': MoreHorizontal,
  circle: Circle,
};

/** Ordered names for the icon picker grid. */
export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

/** Default icon for a brand-new category / an unknown name. */
export const DEFAULT_ICON_NAME = 'circle';

/** Resolve a stored icon_name to a component, falling back to a neutral circle. */
export function iconByName(name: string | null | undefined): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || Circle;
}
